services:
  ai-service:
    build: ./services
    env_file:
      - ../.env
    ports:
      - "50051:50051"

  go-backend:
    build: ./api
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    environment:
      - GRPC_SERVER_ADDRESS=ai-service:50051
    depends_on:
      - ai-service